# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_id',
        ),
    ]
